services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: shkn12
      POSTGRES_DB: chat_center
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

  mongo:
    image: mongo:6-jammy
    environment:
      MONGO_INITDB_DATABASE: chat_center
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=production
      - DEBUG=True
      - POSTGRES_URL=postgres://postgres:shkn12@postgres/chat_center
      - MONGODB_URL=mongodb://mongo:27017
      - MONGODB_NAME=chat_center
      - MONGODB_MESSAGES_COLLECTION=messages
      - REDIS_URL=redis://redis:6379/0
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - NLP_MODEL_NAME=en_core_web_sm
      - SECRET_KEY=5cabdb656c85c687c94956a8aba28258683f962cfaed2d00665f6fd7a41320d8
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      mongo:
        condition: service_started
    healthcheck:
      test: [ "CMD-SHELL", "python -c \"import spacy; spacy.load('ru_core_news_md')\"" ]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
  redis_data:
  mongo_data:
