greeting:
  patterns:
    - ["салом"]
    - ["ҳайр"]
    - ["субҳ ба хайр"]
    - ["рӯз ба хайр"]
    - ["бегоҳ ба хайр"]
  responses:
    - "Салом {name}! {emoji} Чӣ тавр ман метавонам кумак кунам?"
    - "Ҳайр! {emoji} Имрӯз чӣ хел кумак лозим аст?"

farewell:
  patterns:
    - ["худо ҳофиз"]
    - ["то дидор"]
    - ["баъдӣ"]
  responses:
    - "Худо ҳофиз! {emoji} Рӯзи хуб!"
    - "То дидор! {emoji}"

weather:
  patterns:
    - ["обу ҳаво"]
    - ["ҳарорат"]
    - ["пешбини"]
    - ["обу ҳаво чӣ хел аст"]
    - ["борон меборад"]
  responses:
    - "Дар кадом шаҳр шумо обу ҳаворо мехоҳед?"
    - "Номи шаҳрро гӯед, ман обу ҳаворо месанҷам."

provide_city:
  patterns:
    - ["[LOC]"]
    - ["душанбе"]
    - ["ваҳдат"]
    - ["хӯҷанд"]
    - ["бишкек"]
  responses:
    - "Дар {city} офтобӣ, 25°C."
    - "Дар {city} абрҳои пароканда, 22°C."

company:
  patterns:
    - ["ҳизматҳои ширкат"]
    - ["ширкати шумо чӣ мекунад"]
    - ["дар бораи ширкати шумо"]
    - ["чӣ пешниҳод мекунед"]
    - ["таърихи ширкат"]
    - ["мақсади ширкат"]
    - ["ширкат дар куҷо ҷойгир аст"]
  responses:
    - "Мо ҳаллиҳои пешрафтаи технологӣ пешниҳод мекунем."
    - "Хизматҳои мо: зеҳни сунъӣ, булурҳо ва амнияти сиберӣ."
  
  services:
    - "Ҳалли зеҳни сунъӣ ва омӯзиши мошинӣ"
    - "Хизматҳои инфрасохтори абрӣ"
    - "Амнияти сиберӣ"
    - "Таҳияи нармафзори фардӣ"

  company_facts:
    history: "Соли 2010 таъсис ёфтааст барои инқилоб дар ҳалли технологӣ."
    mission: "Таҳкими тиҷорат тавассути ҳалли навоварона."
    employees: "Беш аз 500 корманд дар саросари ҷаҳон."
    location: "Маркази асосӣ дар Водии Силикон."

support:
  patterns:
    - ["кумак"]
    - ["дастгирӣ"]
    - ["мушкилот"]
    - ["хато"]
    - ["ворид намешавам"]
  responses:
    - "Лутфан мушкилиатонро тавсиф кунед."
    - "Бо кадом мушкил рӯ ба рӯ шудед?"
  
  followups:
    login:
      keywords: ["логин", "парол", "воридшавӣ"]
      question: "Мушкилот бо воридшавӣ?"
      responses:
        - "Барои аз нав кардани парол тугмаи 'Парол фаромӯш шуд'-ро пахш кунед. Кумak кард?"
        - "Ҳарфи калонро санҷед. Кумaки иловагӣ лозим аст?"
    
    payment:
      keywords: ["пардохт", "ҳисоб", "пул"]
      question: "Мушкилот бо пардохт?"
      responses:
        - "Ҳисобҳо дар бахши 'Пардохтҳо' дастрасанд. Ҳал шуд?"
        - "Ба бахши молиявӣ пайваст шавам?"
    
    other:
      question: "Тафсилоти бештар диҳед."
      responses:
        - "Кадом хатогӣ мебинед?"
        - "Дар кадом саҳифа мушкил ба амал омад?"