greeting:
  patterns:
    - ["привет"]
    - ["здравствуйте"]
    - ["приветик"]
    - ["доброе", "утро"]
    - ["добрый", "день"]
    - ["здорово"]
  responses:
    - "Привет, {name}! {emoji} Чем могу помочь сегодня?"
    - "Здравствуйте {name}! {emoji} Что могу для вас сделать?"
  fallback: "Привет! Чем могу помочь сегодня?"

farewell:
  patterns:
    - ["пока"]
    - ["до", "свидания"]
    - ["увидимся"]
    - ["до", "встречи"]
  responses:
    - "До свидания! {emoji} Хорошего дня!"
    - "Увидимся скоро! {emoji}"
  fallback: "До свидания! Хорошего дня!"

weather:
  patterns:
    - ["погода"]
    - ["какая", "погода"]
    - ["температура"]
    - ["прогноз"]
    - ["идет", "ли", "дождь"]
  responses:
    - "Для какого города хотите узнать погоду?"
    - "Назовите город, и я проверю погоду."
  fallback: "Пожалуйста, укажите название города."

weather_prompt:
  patterns:
    - ["[LOC]"]
    - ["москва"]
    - ["санкт-петербург"]
    - ["новосибирск"]
    - ["екатеринбург"]
    - ["душанбе"]
    - ["вахдат"]
    - ["худжанд"]
    - ["бишкек"]
  responses:
    - "Пожалуйста, укажите название города."
    - "Какой город вас интересует?"
  fallback: "Пожалуйста, укажите название города."

weather_response:
  patterns: []
  responses:
    - "Погода в {city}: {description}, температура {temp}°C"
    - "В {city} сейчас {description}, {temp}°C"
  fallback: "Пожалуйста, укажите название города."

company:
  patterns:
    - ["компания", "услуги"]
    - ["что", "делает", "ваша", "компания"]
    - ["расскажите", "о", "вашей", "компании"]
    - ["что", "вы", "предлагаете"]
    - ["история"]
    - ["компания"]
    - ["миссия"]
    - ["видение"]
    - ["сколько", "сотрудников"]
    - ["где", "вы", "находитесь"]
  responses:
    - "Мы предоставляем передовые технологические решения."
    - "Наши услуги включают ИИ, облачные вычисления и кибербезопасность."
    - "Мы специализируемся на инновационной разработке ПО."
    - "Наша компания предлагает различные технологические решения."
  services:
    - "Решения в области ИИ и машинного обучения"
    - "Услуги облачной инфраструктуры"
    - "Решения в области кибербезопасности"
    - "Разработка ПО на заказ"
  company_facts:
    history: "Основана в 2010 году с целью революционизировать технологические решения."
    mission: "Расширение возможностей бизнеса через инновационные технологии."
    employees: "У нас более 500 сотрудников по всему миру."
    location: "Штаб-квартира в Силиконовой долине с офисами по всему миру."
  fallback: "Можете уточнить, какую информацию о компании вы ищете?"

support:
  patterns:
    - ["помощь"]
    - ["поддержка"]
    - ["проблема"]
    - ["проблемы"]
    - ["вход"]
    - ["проблема", "с", "входом"]
  responses:
    - "Я здесь, чтобы помочь! Опишите вашу проблему."
    - "Конечно—какая у вас проблема?"
  followups:
    login:
      keywords: ["вход", "авторизация", "пароль", "имя пользователя"]
      question: "Это проблема с входом или авторизацией?"
      responses:
        - "Для сброса пароля нажмите 'Забыли пароль' на странице входа. Помогло?"
        - "Убедитесь, что Caps Lock выключен. Нужна помощь со входом?"
    payment:
      keywords: ["оплата", "счет", "инвойс", "платеж"]
      question: "Проблема с оплатой или счетами?"
      responses:
        - "Счета можно посмотреть в разделе Аккаунт → Оплата. Решило проблему?"
        - "Хотите, чтобы я связал вас с нашей командой по платежам?"
    other:
      keywords: []
      question: "Можете предоставить больше деталей, чтобы я направил вас правильно?"
      responses:
        - "Спасибо, сейчас разберусь. Есть сообщения об ошибках?"
        - "Понял. На какой странице или кнопке вы сейчас?"
  fallback: "Можете предоставить больше деталей о проблеме?"