greeting:
  patterns:
    - ["салом"]
    - ["эй"]
    - ["хуб"]
    - ["Шумо", "чӣ","хелед"]
    - ["ассалом"]
    - ["саломчик"]
    - ["субҳ", "ба", "хайр"]
    - ["рӯз", "ба", "хайр"]
    - ["чӣ", "хел"]
  responses:
    - "Салом, {name}! {emoji} Имрӯз чӣ тавр ба шумо кумак кунам?"
    - "Ассалом {name}! {emoji} Чӣ кор карда метавонам?"
  fallback: "Салом! Чӣ тавр ба шумо кумак кунам?"

farewell:
  patterns:
    - ["хайр"]
    - ["худо", "ҳофиз"]
    - ["аллох","хофиз"]
    - ["то", "дидор"]
    - ["баъдтар"]
  responses:
    - "Худо ҳофиз! {emoji} Рӯзи хуб дошта бош!"
    - "Ба зудӣ мебинем! {emoji}"
  fallback: "Худо ҳофиз! Рӯзи хуб дошта бош!"

weather:
  patterns:
    - ["обу", "ҳаво"]
    - ["обу", "ҳаво", "чӣ", "гуна", "аст"]
    - ["ҳарорат"]
    - ["пешгӯии", "обу", "ҳаво"]
    - ["борон", "меборад"]
  responses:
    - "Барои кадом шаҳр обу ҳаворо донистан мехоҳед?"
    - "Номи шаҳрро гӯед, ман обу ҳаворо месанҷам."
  fallback: "Лутфан, номи шаҳрро гӯед."

weather_prompt:
  patterns:
    - ["[LOC]"]
    - ["москва"]
    - ["санкт-петербург"]
    - ["новосибирск"]
    - ["екатеринбург"]
    - ["душанбе"]
    - ["ваҳдат"]
    - ["хуҷанд"]
    - ["бишкек"]
  responses:
    - "Лутфан, номи шаҳрро гӯед."
    - "Кадом шаҳр ба шумо ҷолиб аст?"
  fallback: "Лутфан, номи шаҳрро гӯед."

weather_response:
  patterns: []
  responses:
    - "Обу ҳаво дар {city} барои {time}: {description}, ҳарорат {temp}°C"
    - "Дар {city} барои {time} ҳоло {description}, {temp}°C"
  fallback: "Лутфан, номи шаҳрро гӯед."

company:
  patterns:
    - ["ширкат", "хизматрасониҳо"]
    - ["ширкати", "шумо", "чӣ", "кор", "мекунад"]
    - ["ба", "ман", "дар", "бораи", "ширкати", "шумо", "гуфта", "метавонед"]
    - ["шумо", "чӣ", "пешниҳод", "мекунед"]
    - ["таърих"]
    - ["ширкат"]
    - ["мақсад"]
    - ["рӯъё"]
    - ["чанд", "корманд", "доред"]
    - ["шумо", "дар", "куҷо", "ҷойгир", "ҳастед"]
  responses:
    - "Мо ҳалли пешрафтаи технологӣ пешниҳод мекунем."
    - "Хизматрасониҳои мо ИИ, ҳисоббарории абрӣ ва амнияти киберро дар бар мегиранд."
    - "Мо ба таҳияи инноватсионии нармафзор тахассус дорем."
    - "Ширкати мо ҳалли гуногуни технологӣ пешниҳод мекунад."
  services:
    - "Ҳалли ИИ ва омӯзиши мошин"
    - "Хизматрасониҳои инфрасохтори абрӣ"
    - "Ҳалли амнияти кибер"
    - "Таҳияи нармафзори фармоишӣ"
  company_facts:
    history: "Соли 2010 бо мақсади инқилоб дар ҳалли технологӣ таъсис ёфтааст."
    mission: "Таъмин кардани тиҷорат тавассути ҳалли инноватсионии технологӣ."
    employees: "Мо зиёда аз 500 корманди содиқ дар саросари ҷаҳон дорем."
    location: "Дафтари марказӣ дар Силикон Вэлли бо офисҳо дар саросари ҷаҳон."
  fallback: "Метавонед мушаххас кунед, ки кадом маълумот дар бораи ширкатро меҷӯед?"

support:
  patterns:
    - ["кумак"]
    - ["Кӯмак"]
    - ["Kūmak"]
    - ["дастгирӣ"]
    - ["мушкил"]
    - ["мушкилот"]
    - ["масъалахое"]
    - ["вход"]
    - ["чоп"]
    - ["проблема"]
    - ["мушкили", "вход"]
  responses:
    - "Ман барои кумак ҳастам! Мушкили худро тавсиф кунед."
    - "Албатта—шумо чӣ мушкиле доред?"
  followups:
    login:
      keywords: ["вход", "имзо", "гузарвожа", "номи", "корбар"]
      question: "Оё ин мушкили вход ё аутентификатсия аст?"
      responses:
        - "Барои барқарор кардани гузарвожа, 'Гузарвожаро фаромӯш кардед' дар саҳифаи входро клик кунед. Оё ин кумак кард?"
        - "Боварӣ ҳосил кунед, ки Caps Lock хомӯш аст. Барои вход кумак лозим аст?"
    payment:
      keywords: ["пардохт", "ҳисоб", "инвойс", "пул"]
      question: "Оё шумо бо пардохт ё ҳисоб муаммо доред?"
      responses:
        - "Шумо метавонед инвойсҳоро дар зери Ҳисоб → Пардохт дидед. Оё ин муамморо ҳал кард?"
        - "Мехоҳед, ки ман шуморо бо дастаи пардохти мо пайваст кунам?"
    other:
      keywords: []
      question: "Метавонед тафсилоти бештар диҳед, то ман ба шумо роҳнамоӣ кунам?"
      responses:
        - "Ташаккур—ман инро таҳқиқ мекунам. Оё паёмҳои хато доред?"
        - "Фаҳмидам. Метавонед гӯед, ки дар кадом саҳифа ё тугма ҳастед?"
  fallback: "Метавонед тафсилоти бештар дар бораи муаммо диҳед?"