greeting:
  patterns:
    - "Салом"                # “hello” in Tajiki :contentReference[oaicite:0]{index=0}
    - "Ҳай"                  # “hi” (adapted) 
    - "Эй"                   # “hey” (adapted)
    - "Субҳ ба хайр"         # “good morning” in Tajiki
    - "Рӯз ба хайр"          # “good afternoon” in Tajiki
  responses:
    - "Салом! Чӣ гуна метавонам ба шумо кӯмак расонам?"  
    - "Ҳай! Чӣ кор метавонам барои шумо кунам?"

farewell:
  patterns:
    - "Хайр"                 # “bye” / “goodbye” :contentReference[oaicite:1]{index=1}
    - "Хайр"                 # duplicate for emphasis
    - "То вохӯрӣ"            # “see you”
    - "Баъд"                 # “later”
  responses:
    - "Хайр! Рӯзи хубе дошта бошед!"  
    - "То боздид!"  

weather:
  patterns:
    - "ҳаво"                 # “weather” in Tajiki :contentReference[oaicite:2]{index=2}
    - "температура"          # “temperature” in Tajiki :contentReference[oaicite:3]{index=3}
    - "пешгӯӣ"               # “forecast” in Tajiki 
    - "ҳаво дар"             # “how's the weather in …”
    - "оё дар .* борон меборад"  # “is it raining in …”
  responses:
    - "Биёед ман шароити ҳаворо барои шумо тафтиш кунам."  
    - "Ман метавонам маълумоти обу ҳаворо пешниҳод кунам."  

company:
  patterns:
    - "хизматрасониҳои ширкат"   # “company services”
    - "компанияи шумо чӣ кор мекунад"  # “what does your company do”
    - "дар бораи шумо ба ман нақл кунед" # “tell me about your”
    - "оё шумо пешниҳод мекунед"       # “do you offer”
  responses:
    - "Мо ҳалли гуногуни технологиро пешниҳод мекунем."  
    - "Хизматҳои мо аз ҷумла ҳалли AI ва абрӣ мебошад."  

chatgpt_fallback:
  patterns:
    - "фаҳмонед"            # “explain”
    - "чӣ гуна"             # “how does”
    - "барои чӣ"            # “why is”
    - "ба ман бештар дар бораи .* бигӯед"  # “tell me more about …”
  responses:
    - "Биёед ман маълумоти бештар дар ин бора диҳам."  

support:
  patterns:
    - "кӯмак"               # “help”
    - "ҳимоя"               # “support”
    - "мушкил"              # “problem”
    - "масъала"             # “issue”
  responses:
    - "Чӣ тавр метавонам ба шумо дар ҳалли ин масъала кӯмак кунам?"  
    - "Биёед ман ба шумо дар ҳал кардани ин мушкил ёрдам расонам."  
