greeting:
  patterns:
    - ["здравствуйте"]
    - ["привет"]
    - ["доброе утро"]
    - ["добрый день"] 
    - ["добрый вечер"]
    - ["салом"]              # Tajik
    - ["ҳайр"]               # Tajik
    - ["субҳ ба хайр"]       # Tajik
    - ["рӯз ба хайр"]       # Tajik
    - ["бегоҳ ба хайр"]     # Tajik
    - ["здорово"]           # New
    - ["приветики"]         # New informal
    - ["салам алейкум"]     # New Tajik
    - ["шуморо чи хел"]     # New Tajik
  responses:
    - "Здравствуйте {name}! {emoji} Чем могу помочь?"
    - "Привет! {emoji} Как я могу вам помочь сегодня?"
    - "Рад вас видеть! {emoji} Что вас интересует?"  # New
    - "Салом ба хуш омадед! {emoji}"                 # New Tajik

farewell:
  patterns:
    - ["пока"]
    - ["до свидания"]
    - ["увидимся"] 
    - ["всего доброго"]
    - ["худо ҳофиз"]        # Tajik
    - ["то дидор"]          # Tajik
    - ["баъдӣ"]             # Tajik
    - ["до завтра"]         # New
    - ["спокойной ночи"]    # New
    - ["ба фароғат"]        # New Tajik
  responses:
    - "До свидания! {emoji} Хорошего дня!"
    - "Увидимся! {emoji}"
    - "Всего наилучшего! {emoji}"                   # New
    - "Хафту хуб дошта бошед! {emoji}"              # New Tajik

weather:
  patterns:
    - ["погода"]
    - ["температура"] 
    - ["прогноз"]
    - ["какая погода"]
    - ["идёт дождь"]
    - ["обу ҳаво"]          # Tajik
    - ["ҳарорат"]           # Tajik
    - ["пешбини"]           # Tajik
    - ["обу ҳаво чӣ хел аст"]  # Tajik
    - ["борон меборад"]     # Tajik
    - ["будет ли снег"]     # New
    - ["сколько градусов"]  # New
    - ["ветрено сегодня"]   # New 
    - ["туманно сейчас"]    # New
    - ["ҳаво чанд аст"]     # New Tajik
    - ["бориш меорад"]      # New Tajik
  responses:
    - "В каком городе вас интересует погода?"
    - "Скажите город, и я проверю погоду."
    - "Для точного прогноза укажите город {emoji}"  # New
    - "Обу ҳавои кадом шаҳр шуморо ҷалб мекунад?"   # New Tajik

provide_city:
  patterns:
    - ["[LOC]"]
    - ["душанбе"] 
    - ["вахдат"]
    - ["худжанд"]
    - ["бишкек"]
    - ["ваҳдат"]            # Tajik
    - ["хӯҷанд"]            # Tajik
    - ["москва"]            # New
    - ["санкт-петербург"]   # New
    - ["истаравшан"]        # New Tajik
    - ["қӯрғонтеппа"]       # New Tajik
  responses:
    - "Сейчас в {city} солнечно, 25°C."
    - "В {city} переменная облачность, 22°C."
    - "В {city} ожидается {condition}, {temp}°C"     # New
    - "Дар {city} ҳаво {condition}, ҳарорат {temp}°C" # New Tajik

company:
  patterns:
    - ["услуги компании"]
    - ["чем занимается ваша компания"] 
    - ["расскажите о вашей компании"]
    - ["что вы предлагаете"]
    - ["история компании"]
    - ["миссия компании"]
    - ["где вы находитесь"]
    - ["ҳизматҳои ширкат"]   # Tajik
    - ["ширкати шумо чӣ мекунад"]  # Tajik
    - ["дар бораи ширкати шумо"]   # Tajik
    - ["чӣ пешниҳод мекунед"]      # Tajik
    - ["ваши партнёры"]            # New
    - ["география работы"]         # New
    - ["награды компании"]         # New
    - ["ширкати шумо куҷо ҷойгир аст"] # New Tajik
  responses:
    - "Мы предоставляем передовые технологические решения."
    - "Наши услуги включают ИИ, облачные технологии и кибербезопасность."
    - "Работаем в {count}+ странах с 2015 года 🌍"              # New
    - "Мо дар соҳаи технологияҳои пешқадам фаъолият мекунем"   # New Tajik

support:
  patterns:
    - ["помощь"]
    - ["поддержка"] 
    - ["проблема"]
    - ["ошибка"]
    - ["не могу войти"]
    - ["кумак"]              # Tajik
    - ["дастгирӣ"]           # Tajik
    - ["мушкилот"]           # Tajik
    - ["хато"]               # Tajik
    - ["ворид намешавам"]    # Tajik
    - ["не работает кнопка"] # New
    - ["зависла система"]    # New
    - ["пропал доступ"]      # New
    - ["системаҳо кор намекунанд"] # New Tajik
  responses:
    - "Опишите, пожалуйста, вашу проблему."
    - "С какой проблемой вы столкнулись?"
    - "Попробуйте эти шаги: 1) Перезагрузка 2) Очистка кеша 🔄" # New
    - "Барои ёрии зуд ба мо телефон занед: +992 123 456 789 ☎️" # New Tajik

  followups:
    login:
      keywords: ["логин", "пароль", "вход"]
      question: "Это проблема с авторизацией?"
      responses:
        - "Для сброса пароля нажмите 'Забыли пароль'. Помогло?"
        - "Проверьте регистр букв. Нужна дополнительная помощь?"
        - "Возможно, аккаунт временно заблокирован 🔐"          # New
        - "Срок действия пароля истёк? Попробуйте обновить его" # New
    
    payment:
      keywords: ["оплата", "счёт", "платёж"]
      question: "Проблема с оплатой?"
      responses:
        - "Счета доступны в разделе 'Платежи'. Решило проблему?"
        - "Соединить с финансовым отделом?"
        - "Проверьте баланс карты 💳"                           # New
        - "Платёжные системы временно недоступны 🚧"            # New
    
    other:
      question: "Опишите подробнее проблему."
      responses:
        - "Какие именно ошибки вы видите?"
        - "На какой странице возникает проблема?"
        - "Скриншот ошибки поможет быстрее решить вопрос 📸"     # New
        - "Включите VPN и попробуйте снова 🌐"                  # New